### ISSUE TITLE
Evaluation timed out on external submission

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#132]
The 33678 submission just hit the 12 hour evaluation timeout and was cancelled. Pre-cancellation, I think the RMSD evaluations were working. They were just taking a while. 

The submitted structures look reasonable. Notably, they haven't stripped out anything from the original candidates -- all of the waters and solvents, and even the original ligands are still there. They are likely the original candidate files with no changes.

**Comment by j-wags** [comment]
Update -- Adding -groupwaters to the docked receptor splitting command sped this up significantly. 

New docked receptor splitting command: `commands.getoutput("$SCHRODINGER/run split_structure.py -groupwaters -many_files -m molecule %s docked_molecules.pdb" %(docked_receptor))`

Evaluation still gets hung up on 5g1a, with greater than 10,000 "match" files being created. I think this is a problem with being unable to distinguish solvents in the docked receptors from protein chains, and the solvents in the xtal structure from our ligand of interest. We should implement better logic for this.

As a side note, we're not checking that the submitted ligand is the challenge ligand. If someone correctly docked an organic solvent (or some molecule other than the challenge ligand) that appeared in the final xtal structure, that would be scored.

I'm out of town for the weekend, but if anyone wants to check this out, I'm working on this on nif1 in /var/home/j5wagner/new_home_dir/2017_04_13_33678_submission_fixing

**Comment by shuail** [comment]
Worked on this last week briefly, it seems that the evaluator create some abounded files which makes the RMSD calculation slow. Will have some time to work on this issue today and run test on shuaidev first.

**Comment by j-wags** [comment]
Meeting notes:
* We should remove all molecules containing less than 100 atoms from being considered as protein chains for alignment
* We should track the submitted docked mol through its combination with the docked receptor and alignment
?Did I forget anything?

**Comment by j-wags** [comment]
Ideal evaluation algorithm:
run a mol file validation to ensure docked.mol is the challenge ligand by using the ligand information we released.
Merge docked.mol into docked.pdb to make docked_complex
Identify all instances of the xtal ligand
for each xtal ligand:
     Do binding site alignment of docked_complex to xtal complex where the binding site is defined by this xtal ligand
     Extract docked.mol back out of docked_complex
     Calculate ligand RMSD
This RMSD = minimum of all possible ligand RMSDs

**Comment by j-wags** [comment]
@j-wags will work on processing 33678 submissions promptly by hand while the above is implemented. @j-wags will also assemble test cases to ensure that the new algorithm works as intended in difficult situations. @shuail will work on implementing the above algorithm.

**Comment by shuail** [comment]
rewrite the evaluate.py to implement:
1, Align the docked complex using the binding site alignment for each of the crystal template and calculate the RMSD, if the binding site alignment failed, then the whole protein alignment will be applied.
2, Improve the extraction step in the evaluate.py to ensure the RMSD calculating was only applied to the docked ligand but not all others ligand like solvents or co-factors
3,  Add the ligand center calculation step in the evaluate.py to output the distance of the docked ligand with the crystal ligand. Also calculate the distance between the original LMCSS ligand center with the crystal ligand center.

**Comment by coleslaw481** [comment]
Shuai has implemented 1) and 3) above, which has prevented the recurrence of these errors.
