### ISSUE TITLE
create json file for evaluation results

### ISSUE THREAD

**Issue by mchiu** [drugdata/D3R#143]
To create a web report, it'd be helpful to have a json file of the evaluation results text file.

**Comment by mchiu** [comment]
[pickle2json.zip](https://github.com/drugdata/D3R/files/1062491/pickle2json.zip)

temp_rmsd.pickle - input file
pickle2json.py - conversion script
temp_rmsd.txt - output file after running "python ./pickle2json.py > temp_rmsd.txt"

Nothing fancy here, but it does the job ...

import os
import pickle
import json

class Object:
    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__,
            sort_keys=True, indent=4)

objects = []

def obj_dict(obj):
    return obj.__dict__

def read_from_pickle(path):
    with open(path, 'rb') as file:
        try:
                objects.append(pickle.load(file))
        except EOFError:
                pass

read_from_pickle("temp_rmsd.pickle")

print json.dumps(objects, default=obj_dict)

**Comment by j-wags** [comment]
I still need to get RMSD.json uploaded to box -- Probably in the "get_uploadable_files" function

**Comment by j-wags** [comment]
The json validated successfully on https://jsonlint.com/

**Comment by coleslaw481** [comment]
Jeff got evaluation.py to generate RMSD.json file in an earlier commit, but this commit fixed a typo in his commit: 8054c7733cfeeafa21a9ae5881a464fe143b5e3d
