### ISSUE TITLE
Disregard any files in the SuppInfo folder

### ISSUE THREAD

**Issue by mchiu** [drugdata/D3R#167]
Disregard any files in the SuppInfo folder. Here's an example of a file that threw an error that shouldn't have:
Pose1b/SuppInfo/ligand_rotated-CatS_9.mol

**Comment by coleslaw481** [comment]
Thinking to add --excludedir option that accepts comma delimited list with default set to SuppInfo
and in molfilevalidator._molfile_from_tarfile_generator() add logic that calls
os.path.dirname(tarinfo.name) and the splitting that entry into list and excluding if entry contains entries from --excludedir list.

**Comment by coleslaw481** [comment]
Fixed in commit: 
1f258c1..6b8aa77  chrisdev -> chrisdev
