### ISSUE TITLE
Week 45 32517_non-candidate-structures failed unpacking at stage 6

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#169]
The stage 6 download worked, but the unpacking of the downloaded tar.gz file failed, and therefore the submission was not evaluated. This happened on both hobo and hobo2.

First sign of error is at /celpp/data/2017/dataset.week.45/stage.6.32517_non-candidate-structures.extsubmission/error

 I was able to successfully unpack them manually with tar -xvzf, and am evaluating manually.

**Comment by j-wags** [comment]
Potentially related -- The 32517 and 32517-non_candidate_structures submissions this week were accidentally the same file.

**Comment by coleslaw481** [comment]
Output from **error** file in the above directory is:

```Bash
Caught exception [Errno 2] No such file or directory: '/celpp/data/2017/dataset.week.45/stage.6.32517_non-candidate-structures.extsubmission/celpp_week45_2017_dockedresults_32517_non-candidate-structures'
```

For this submission the code expects the directory within the tarfile to be:

```Bash
celpp_week45_2017_dockedresults_32517_non-candidate-structures/
```

What was in the tar file was actually this directory:
```Bash
celpp_week45_2017_dockedresults_32517/
```

This is not a bug since the directory is supposed to match the id_name format.

**Comment by coleslaw481** [comment]
Might be a good idea to make the error message more readable. Perhaps state code was looking for directory X, but only saw directory Y.

**Comment by coleslaw481** [comment]
Improved the error message for this case. Code will now raise a ChallengePackageFormatError with more human readable text if the challenge package directory is not named correctly. This output will end up the error file for the task.

048f62b..69c956a  chrisdev -> chrisdev
