### ISSUE TITLE
Remove hardcoded paths from vinadocking.py

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#24]
Hi Jeff,
  I will make sure any invocation of vinadocking.py will have the below commands (minus mae2Pdb) will be in the environment path.
 
 Could you remove the hardcoded paths on the following commands:

vina
prepare_ligand.py
prepare_receptor4.py

and a custom generated python script mae2Pdb.py

This includes removing the pythonsh or python command prefix.  

thanks,

chris

**Comment by j-wags** [comment]
Hi Chris,

I have a build ready to go with the assumption that the prepare_ scripts will be in the PATH. My best guess is that you will source /usr/local/mgltools/bin/mglenv.sh before running. However the prepare_ scripts are not in the PATH set by the mglenv.sh, and short of manually adding the prepare_ scripts' directory into PATH, I can not test to verify the code will work. 

Would it be acceptable to attach a variable-based path to the prepare_ scripts (in the form of  $MGL_ROOT/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py) ? MGL_ROOT is defined by mglenv.sh.

I'll be down there tomorrow for the meeting anyway if it's easier to discuss in person.

Thanks,
Jeff

**Comment by coleslaw481** [comment]
You guessed correctly I am planning to source mglenv.sh before invoking celpp pipeline.  So, yes it is a good idea to use your suggested variable-based path for the mgl tools scripts.

chris

**Comment by j-wags** [comment]
Made a fix to replace hardcoded paths with paths relative to $MGL_ROOT - See file vinadocking.py in commit d983c02 .
