### ISSUE TITLE
vinadocking.py switch code to use argparse instead of optparse

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#25]
Hey Jeff,
  Could you switch out optparse for argparse in vinadocking.py.  optparse is deprecated in 2.7 of python and argparse is its successor. 

thanks,

chris

**Comment by j-wags** [comment]
Hi Chris,

mglenv.sh changes python to 2.5.6 (before argparse). One option may be to source mglenv.sh only in the commands.getoutput lines where we call the prepare_ scripts. Let's chat today about this. 

Hooray scientific software.
Jeff

**Comment by coleslaw481** [comment]
Oh, didn't see that in the mglenv.sh script.  Good catch.  Probably have to
write a simple wrapper script around these mgl scripts to hide this issue
from the rest of the code base.

chris

**Comment by coleslaw481** [comment]
created test_vinadocking.py test class and put in one test.  Function main_vina() needs unit tests.  closing ticket since we just deploy and try this code out.
