### ISSUE TITLE
Provide definition for new file from genchallengedata.py

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#34]
Provide definition for readme.txt and wiki for this new file:
largest-&lt;target id&gt;_&lt;candidate id&gt;-&lt;candidateligand id&gt;-lig.pdb

**Comment by coleslaw481** [comment]
Shuai emailed with this definition:


The file contains the 3D coordinate of the atoms for the ligand in the "largest" protein. (I guess the "largest" will be defined somewhere else?)

**Comment by mkgilson** [comment]
This terminology is persistently confusing. It is not the largest 
protein or the largest ligand. It is a shorthand for the ligand with the 
largest common substructure with the ligand to be docked.  How about if 
choose a more descriptive term?

Mike


On 5/6/2016 7:00 AM, Chris Churas wrote:
>
> Shuai emailed with this definition:
>
> The file contains the 3D coordinate of the atoms for the ligand in the 
> "largest" protein. (I guess the "largest" will be defined somewhere else?)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/drugdata/D3R/issues/34#issuecomment-217448031>
>

-- 
Michael K. Gilson, M.D., Ph.D.
Professor, Skaggs School of Pharmacy and Pharmaceutical Sciences
Co-Director, UCSD Center for Drug Discovery Innovation
U. C. San Diego
9500 Gilman Drive
Pharmaceutical Sciences Building, Room 3224
La Jolla, CA 92093-0736
Voice: 858-822-0622
Fax: 858-822-7726
http://gilson.ucsd.edu
http://www.bindingdb.org
http://cddi.ucsd.edu

**Comment by coleslaw481** [comment]
Re opening ticket since it looks like the definition and perhaps the file names need further review.

**Comment by mkgilson** [comment]
Thanks.  Is there a list of definitions and file names handy for review?

Mike

On 5/6/2016 7:10 AM, Chris Churas wrote:
>
> Re opening ticket since it looks like the definition and perhaps the 
> file names need further review.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/drugdata/D3R/issues/34#issuecomment-217450376>
>

-- 
Michael K. Gilson, M.D., Ph.D.
Professor, Skaggs School of Pharmacy and Pharmaceutical Sciences
Co-Director, UCSD Center for Drug Discovery Innovation
U. C. San Diego
9500 Gilman Drive
Pharmaceutical Sciences Building, Room 3224
La Jolla, CA 92093-0736
Voice: 858-822-0622
Fax: 858-822-7726
http://gilson.ucsd.edu
http://www.bindingdb.org
http://cddi.ucsd.edu

**Comment by coleslaw481** [comment]
The contents of the readme.txt packaged with the challenge data tarfile is on this page:
https://github.com/drugdata/D3R/wiki/Proposed-structure-of-weekly-CELPP-data-package-for-pose-predictions

The data dictionary with definitions is here:
https://github.com/drugdata/d3r/wiki/Data-dictionary

**Comment by shuail** [comment]
When I wrote that definition, I think the quoted "largest" should be fully
defined at the same page ie in the upper readme file or the hyperlink in
the wiki page similar like other definitions like "smallest", "target" etc.
So I quoted it to say that we need to refer this to somewhere else to avoid
redefining it. It's not very easy to make it self defined I guess. It is
the largest MCSS comparing with the ligand to be docked, but it's also not
a designed ligand or any ligands in the PDB. It must be the ligand in the
protein which passed the criteria of the blastnfilter. So it comes back to
the definition of the "largest" protein...

Thanks,
Shuai

**Comment by mkgilson** [comment]
Hi Shuai,


The problem comes when someone mentions the “largest protein”. This phrase, on the face of it, means the protein with the greatest molecular weight.  So every time we use this phrase, it is ambiguous and confusing.  I would therefore like to find a different term for the protein with the ligand with the largest MCSS.  Even if the term we choose is not self-defined, it can be an improvement over “largest protein” by not having an alternative meaning.

 

How about “MaxMCSS” and “MinMCSS”?  

 

Mike

**Comment by mkgilson** [comment]
Hm, thinking further, how about MaxMCSS Candidate and MinMCSS Candidate?
Mike

On 5/6/2016 9:14 AM, shuail wrote:
> When I wrote that definition, I think the quoted "largest" should be fully
> defined at the same page ie in the upper readme file or the hyperlink in
> the wiki page similar like other definitions like "smallest", "target" 
> etc.
> So I quoted it to say that we need to refer this to somewhere else to 
> avoid
> redefining it. It's not very easy to make it self defined I guess. It is
> the largest MCSS comparing with the ligand to be docked, but it's also not
> a designed ligand or any ligands in the PDB. It must be the ligand in the
> protein which passed the criteria of the blastnfilter. So it comes back to
> the definition of the "largest" protein...
>
> Thanks,
> Shuai
>
> On Fri, May 6, 2016 at 7:21 AM, Chris Churas <notifications@github.com>
> wrote:
>
> > The contents of the readme.txt packaged with the challenge data 
> tarfile is
> > on this page:
> >
> > 
> https://github.com/drugdata/D3R/wiki/Proposed-structure-of-weekly-CELPP-data-package-for-pose-predictions
> >
> > The data dictionary with definitions is here:
> > https://github.com/drugdata/d3r/wiki/Data-dictionary
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/drugdata/D3R/issues/34#issuecomment-217453111>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/drugdata/D3R/issues/34#issuecomment-217487624>
>


-- 
Michael K. Gilson, M.D., Ph.D.
Professor, Skaggs School of Pharmacy and Pharmaceutical Sciences
Co-Director, UCSD Center for Drug Discovery Innovation
U. C. San Diego
9500 Gilman Drive
Pharmaceutical Sciences Building, Room 3224
La Jolla, CA 92093-0736
Voice: 858-822-0622
Fax: 858-822-7726
http://gilson.ucsd.edu
http://www.bindingdb.org
http://drugdiscovery.ucsd.edu
http://drugdesigndata.org

**Comment by shuail** [comment]
I see the point, yes that makes sense to me! So how about changing the
definition to

The file contains the 3D coordinate of the atoms for the ligand in the
MaxMCSS("largest") candidate?

Where the quoted "largest" is the hyperlink to the full definition. Do you
also suggest to change all "largest" to "MaxMCSS" in all other filenames?
If so, I need to change the code correspondingly.

Thanks,
Shuai

**Comment by mkgilson** [comment]
I'm not sure exactly what changes would need to be made.  Fundamentally, 
what I want to get away from is talking about the largest protein.  I'd 
rather talk about the MaxMCSS protein or something like that.

On 5/6/2016 9:47 AM, shuail wrote:
> I see the point, yes that makes sense to me! So how about changing the
> definition to
>
> The file contains the 3D coordinate of the atoms for the ligand in the
> MaxMCSS("largest") candidate?
>
> Where the quoted "largest" is the hyperlink to the full definition. Do you
> also suggest to change all "largest" to "MaxMCSS" in all other filenames?
> If so, I need to change the code correspondingly.
>
> Thanks,
> Shuai
>
> On Fri, May 6, 2016 at 9:23 AM, mkgilson <notifications@github.com> wrote:
>
> > Hi Shuai,
> >
> >
> > The problem comes when someone mentions the “largest protein”. This
> > phrase, on the face of it, means the protein with the greatest molecular
> > weight. So every time we use this phrase, it is ambiguous and 
> confusing. I
> > would therefore like to find a different term for the protein with the
> > ligand with the largest MCSS. Even if the term we choose is not
> > self-defined, it can be an improvement over “largest protein” by not 
> having
> > an alternative meaning.
> >
> >
> >
> > How about “MaxMCSS” and “MinMCSS”?
> >
> >
> >
> > Mike
> >
> >
> >
> > From: shuail [mailto:notifications@github.com]
> > Sent: Friday, May 6, 2016 9:15 AM
> > To: drugdata/D3R <D3R@noreply.github.com>
> > Cc: mkgilson <mgilson@ucsd.edu>; Comment <comment@noreply.github.com>
> > Subject: Re: [drugdata/D3R] Provide definition for new file from
> > genchallengedata.py (#34)
> >
> >
> >
> > When I wrote that definition, I think the quoted "largest" should be 
> fully
> > defined at the same page ie in the upper readme file or the hyperlink in
> > the wiki page similar like other definitions like "smallest", 
> "target" etc.
> > So I quoted it to say that we need to refer this to somewhere else 
> to avoid
> > redefining it. It's not very easy to make it self defined I guess. It is
> > the largest MCSS comparing with the ligand to be docked, but it's 
> also not
> > a designed ligand or any ligands in the PDB. It must be the ligand 
> in the
> > protein which passed the criteria of the blastnfilter. So it comes 
> back to
> > the definition of the "largest" protein...
> >
> > Thanks,
> > Shuai
> >
> > On Fri, May 6, 2016 at 7:21 AM, Chris Churas <notifications@github.com>
> > wrote:
> >
> > > The contents of the readme.txt packaged with the challenge data 
> tarfile
> > is
> > > on this page:
> > >
> > >
> > 
> https://github.com/drugdata/D3R/wiki/Proposed-structure-of-weekly-CELPP-data-package-for-pose-predictions
> > >
> > > The data dictionary with definitions is here:
> > > https://github.com/drugdata/d3r/wiki/Data-dictionary
> > >
> > > —
> > > You are receiving this because you were assigned.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/drugdata/D3R/issues/34#issuecomment-217453111>
> > >
> >
> >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/drugdata/D3R/issues/34#issuecomment-217487624>
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/drugdata/D3R/issues/34#issuecomment-217489758>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/drugdata/D3R/issues/34#issuecomment-217495289>
>


-- 
Michael K. Gilson, M.D., Ph.D.
Professor, Skaggs School of Pharmacy and Pharmaceutical Sciences
Co-Director, UCSD Center for Drug Discovery Innovation
U. C. San Diego
9500 Gilman Drive
Pharmaceutical Sciences Building, Room 3224
La Jolla, CA 92093-0736
Voice: 858-822-0622
Fax: 858-822-7726
http://gilson.ucsd.edu
http://www.bindingdb.org
http://drugdiscovery.ucsd.edu
http://drugdesigndata.org

**Comment by coleslaw481** [comment]
Added following definition to readme for the new *-lig.pdb file:

-- Contains the 3D coordinate of the atoms for the ligand
                       in the MaxMCSS candidate (largest) protein.
