### ISSUE TITLE
Vina and Glide workflows fail on different proteins for different reasons

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#42]
This is more of a placeholder for a wide range of outstanding issues to track down in the long term. Some notes:
- Glide will crash if there are no receptor atoms in the box. Vina will not, it'll just put the ligands somewhere in space.
- The vina workflow may barf and give up when given charged ligands.
- In some cases, the box is just badly misplaced (eg if largest has two nearly identical domains, we choose to dock around the ligand in domain A but our apo structure just happened to choose to align to domain B). This either crashes the docking or causes it to be far off target.

Here's a picture of the evaluate results from Jeff's validation run on the week 19 data.
![2016 06 02 16 43 35](https://cloud.githubusercontent.com/assets/16329175/15764637/4e062cd8-28e1-11e6-836f-06016282956f.jpg)

I think that Glide covers more targets because it can handle charged ligands (remember: one ligand per target). On the other hand, Vina fails on less candidates because it can dock without receptor in the box (but these cases jack up its average RMSD, whereas in Glide they are simply blank.)

**Comment by coleslaw481** [comment]
This is a bit too generic and glide/vina workflows are being phased out of celpp pipeline as of 1.9.0
