### ISSUE TITLE
Change Glide from XP to SP

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#50]
Or make a second Glide docking submission...

**Comment by j-wags** [comment]
Done. Added the "-x"  flag to glidedocking.py, which tells it to use XP. By default, it will now use SP. This fix was implemented in branch jeff_glide_sp. To minimize the number of pull requests, I'll merge this in with other recent fixes and make one big submission.

I verified that this runs in /var/home/j5wagner/2016_07_14_glide_sp_conversion/bigtest

Timing differences on a small test case are minimal - roughly 2.97 minutes/ligand for XP vs. 2.61 minutes/ligand for SP. This time includes grid generation, which is the same for both SP and XP.

**Comment by mkgilson** [comment]
why choose sp over xp?
thx
MIke

**Comment by j-wags** [comment]
This was a somewhat old idea - We think that it reflects the way that most people use glide. I've left in the -x flag so that we can easily modify the cron job in the future to generate two glide jobs-  one SP and one XP.

**Comment by mkgilson** [comment]
I see, thx
MIke

**Comment by j-wags** [comment]
Meeting note - just pull request this now

**Comment by j-wags** [comment]
Closed by commit 57552adfd2818f020bfd15c4ec2c17dc14c8252d
