### ISSUE TITLE
Update rdkit package to 2016.03.2 version 

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#57]

**Comment by coleslaw481** [comment]
2016.03.2 according to github (https://github.com/rdkit/rdkit/releases) came out May 20 and it looks like the standard installation channels (yum install via giallu repo) have not been updated.  

At the moment these are the versions for centos 6:

Installed Packages
python-rdkit.x86_64                  2015.03.1-2.el6               @giallu-rdkit
rdkit.x86_64                         2015.03.1-2.el6               @giallu-rdkit
Available Packages
rdkit-debuginfo.x86_64               2015.03.1-2.el6               giallu-rdkit 
rdkit-devel.x86_64                   2015.03.1-2.el6               giallu-rdkit 
rdkit-doc.noarch                     2015.03.1-2.el6               giallu-rdkit 
rdkit-extras.noarch                  2015.03.1-2.el6               giallu-rdkit 
rdkit-postgresql.x86_64              2015.03.1-2.el6               giallu-rdkit 

To get the latest and greatest would require custom compilation of this package.  Should I request this from the systems team?

**Comment by j-wags** [comment]
Unfortunately we really need a 2016.03 version, so we'll have to bug the
sysadmins. I had the same experience, and always have to build manually.

**Comment by coleslaw481** [comment]
I will make a request.

**Comment by coleslaw481** [comment]
Created ticket: CRBS-11252

**Comment by j-wags** [comment]
We've got at least a minimal solution to this now. In the interest of de-cluttering the issue tracker, I'll pull this down.
