### ISSUE TITLE
Install pymol on nif1

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#59]
Sorry to spam you with software stuff, Chris. Please let me know if you'd like these requests in a different format or if I should contact a nif1 sysadmin directly.

**Comment by coleslaw481** [comment]
The open source pymol or the pay version: (http://www.pymolwiki.org/index.php/Linux_Install)  Also does version 1.6 new enough?  1.6.0 is the version in the yum repo and would be easier for the admin to install.

**Comment by j-wags** [comment]
Open source should be sufficient, and I think 1.6 will have what we need.

**Comment by coleslaw481** [comment]
I created a ticket (CRBS-11251) requesting the installation

**Comment by coleslaw481** [comment]
pymol has been installed on nif1.  Please verify it works for you and close this ticket.
