### ISSUE TITLE
Change candidate category names

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#66]
Largest --> LMCSS
Smallest --> SMCSS
Apo --> HiResApo
Holo --> HiResHolo

**Comment by j-wags** [comment]
Work on wrapping this in a generic CELPPade wrapper that contestants can re-use

**Comment by j-wags** [comment]
I've updated the wiki pages (all 42 of them) and am testing the new file naming conventions in /var/home/j5wagner/2016_07_28_candiate_name_change_validation/test1 on nif1.

Still to do: Update our sample data

**Comment by mkgilson** [comment]
thanks!

**Comment by j-wags** [comment]
Resolved by pull request #71
