### ISSUE TITLE
Even if given custom step scripts, celpprunner still uses utilities from the installed version of d3r

### ISSUE THREAD

**Issue by j-wags** [drugdata/D3R#69]
For example, if I run celpprunner with a custom --blastnfilter commandline argument, the "import d3r.utilities.writers" in that blastnfilter script still imports from the default system d3r installation. This has made testing kind of difficult, but I also understand that it's tough to agree on desired behavior in this case so we might just choose to remove this ticket.

**Comment by shuail** [comment]
Hi Jeff,

I think that's related to the python path environment. So if d3r is
installed, the default d3r installation folder will be registered to the
python path. One thing may help is to run your local version of
blastnfilter under your local d3r folder like

python d3r/blastnfilter.py --options with absolute path to the files. In
this case, I guess the program will search for the utilities under this
local folder first.

Thanks,
Shuai

**Comment by j-wags** [comment]
Thanks, Shuai. Yeah, I've started testing as the d3r user and learned that I need to overwrite the default python path. It took me a while, though. 

In hindsight, this is a silly ticket - Chris was right all along - We should just prioritize setting up an actual test platform.
