### ISSUE TITLE
Improve documentation in RMSD.txt

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#83]
Mike asked: 

What does "Valid cases" mean? Does this mean RMSD greater than some threshold?  And we show a separate average over only these cases?

The part of the RMSD.txt he is referring to:

=====Total number of query protein: 32 =====
Valid cases         28        28        10        28        28
Average             7.367     7.986     14.194    7.727     7.782
=====Abnormal RMSDs =====

**Comment by shuail** [comment]
add an explanation for the phase "abnormal RMSDs"

**Comment by shuail** [comment]
The current version of that line is:

=====Abnormal RMSDs (LMCSS cases where the RMSD > 8.0)=====
