### ISSUE TITLE
Download new tsv file in data import stage

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#84]
Although not official yet, but odds are this file will need to be downloaded in the data import task. Before working on this task.

File to download:
http://wwpdb.org/files/new_release_structure_sequence_canonical.tsv

**Comment by coleslaw481** [comment]
Shuai let me know if you want this new tsv file downloaded

**Comment by shuail** [comment]
Hi Chris, yes let's use the new "canonical" file. Thanks!

**Comment by coleslaw481** [comment]
Going to make this change.

**Comment by coleslaw481** [comment]
Committed untested fix:
 8c82b98..7eec32b  chrisdev -> chrisdev

DataImportTask has new method get_oldsequence_tsv() and DataImportTask also downloads old and new sequence tsv. BlastNFilterTask now checks for sequence.tsv file and if it does not exist it falls back to old sequence tsv.

**Comment by coleslaw481** [comment]
Merged changes into master
